modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/arm32x/leather-blocks/issues"
license = "MPL-2.0"

[[mods]]
modId = "leatherblocks"
version = "${version}"
displayName = "Leather Blocks"
authors = "ARM32"
description = '''
Adds a leather block to the game which can be dyed like leather armor.
'''
logoFile = "icon.png"

[[dependencies.leatherblocks]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.leatherblocks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.leatherblocks]]
modId = "architectury"
mandatory = true
versionRange = "[3.2.47,)"
ordering = "AFTER"
side = "BOTH"